// Generated by CoffeeScript 1.3.3
(function() {
  var autoLink,
    __slice = [].slice;

  autoLink = function() {
    var key, limit, link_attributes, omission, options, url_pattern, value, _ref;
    options = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    url_pattern = /(\b(https?):\/\/[\-A-Z0-9+&@#\/%?=~_|!:,.;]*[\-A-Z0-9+&@#\/%=~_|])/ig;
    if (options.length > 0) {
      omission = options[0].omission || '...';
      delete options[0].omission;
      limit = options[0].limit;
      delete options[0].limit;
      link_attributes = '';
      _ref = options[0];
      for (key in _ref) {
        value = _ref[key];
        link_attributes += " " + key + "='" + value + "'";
      }
      return this.replace(url_pattern, function(match, url) {
        var displayUrl;
        displayUrl = url;
        if (limit) {
          displayUrl = displayUrl.replace(/https?:\/{2}/, '');
          if (displayUrl.length > limit) {
            displayUrl = "" + (displayUrl.substr(0, limit - omission.length)) + omission;
          }
        }
        return "<a href='" + url + "'" + link_attributes + ">" + displayUrl + "</a>";
      });
    } else {
      return this.replace(url_pattern, "<a href='$1'>$1</a>");
    }
  };

  String.prototype['autoLink'] = autoLink;

}).call(this);
